// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzoSYM4D5GmqUxL682KBwU1SkKTovCXs',
    appId: '1:866446787256:web:7a2edf37aca23ec79dea4d',
    messagingSenderId: '866446787256',
    projectId: 'roadmap-2908',
    authDomain: 'roadmap-2908.firebaseapp.com',
    storageBucket: 'roadmap-2908.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCVaqMI4wDwauDOEX5IHBZMfXdfMZMaWk',
    appId: '1:866446787256:android:ea5f962fe17d877c9dea4d',
    messagingSenderId: '866446787256',
    projectId: 'roadmap-2908',
    storageBucket: 'roadmap-2908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiAxsddS2778ygWVvsNtuncA2WzqN2lPc',
    appId: '1:866446787256:ios:fefea0142dc89e189dea4d',
    messagingSenderId: '866446787256',
    projectId: 'roadmap-2908',
    storageBucket: 'roadmap-2908.firebasestorage.app',
    iosBundleId: 'com.example.careerSimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiAxsddS2778ygWVvsNtuncA2WzqN2lPc',
    appId: '1:866446787256:ios:fefea0142dc89e189dea4d',
    messagingSenderId: '866446787256',
    projectId: 'roadmap-2908',
    storageBucket: 'roadmap-2908.firebasestorage.app',
    iosBundleId: 'com.example.careerSimulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrzoSYM4D5GmqUxL682KBwU1SkKTovCXs',
    appId: '1:866446787256:web:37d1207587995fba9dea4d',
    messagingSenderId: '866446787256',
    projectId: 'roadmap-2908',
    authDomain: 'roadmap-2908.firebaseapp.com',
    storageBucket: 'roadmap-2908.firebasestorage.app',
  );

}